# Generated by Django 5.1.7 on 2025-06-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_rename_latitude_hotel_lat_rename_longitude_hotel_lon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='city',
            field=models.CharField(default='Paris', max_length=100),
            preserve_default=False,
        ),
    ]
